name: GlassDropPlugin
main: de.noonex.glassdropplugin.GlassDropPlugin
version: 0.2

commands:
    glassdrop:
        description: Enable or disable glass drops.
        usage: /glassdrop
    refreshglassdrop:
        description: Reload the config.yml file.
        usage: /refreshglassdrop
