name: ModDropPlugin
main: de.noonex.moddropplugin.ModDropPlugin
version: 0.6

commands:
    md:
        description: Toggle ModDrop or reload the config file. Use /md list to list possible commands.
        usage: /md command
