name: ModDropPlugin
main: de.noonex.moddropplugin.ModDropPlugin
version: 0.3

commands:
    moddrop:
        description: Enable or disable glass drops.
        usage: /moddrop
    refreshmoddrop:
        description: Reload the config.yml file.
        usage: /refreshmoddrop
