name: ModDropPlugin
main: de.noonex.moddropplugin.ModDropPlugin
version: 0.2

commands:
    moddrop:
        description: Enable or disable glass drops.
        usage: /glassdrop
    refreshmoddrop:
        description: Reload the config.yml file.
        usage: /refreshglassdrop
